### ISSUE TITLE
Add ability to error from NSURLSession mocks

### ISSUE THREAD

**Issue by kerrmarin** [net-a-porter-mobile/NSURLSession-Mock#8]
We currently have the ability to mock NSURLConnection to return errors. It would be great to be able to do the same with the mock for NSURLSession.

Presumably we just need to extend NSURLSession to have methods that allow for creation of mocks with error states and then check if there's an error when consuming the request

**Comment by deanWombourne** [comment]
I'm going to take a look at this after the block PR - it's a natural progression, and no-one else has claimed this ticket :)
